const PDFDocument = require('pdfkit');

/**
 * Generate a Medical Appointment Invoice PDF
 * @param {Object} data - Appointment data including populated patient and doctor
 * @param {Object} res - Express response object to stream the PDF
 */
const generateInvoicePDF = (data, res) => {
    const doc = new PDFDocument({ margin: 50 });

    // Stream the PDF to the response
    doc.pipe(res);

    // Header
    doc.fillColor('#444444')
        .fontSize(20)
        .text('HealSync - Medical Consultation Invoice', { align: 'center' });
    
    doc.moveDown();
    doc.fontSize(10).text(`Invoice No: INV-${data._id.toString().substring(0, 8).toUpperCase()}`, { align: 'right' });
    doc.text(`Date Issued: ${new Date().toLocaleDateString()}`, { align: 'right' });
    
    doc.moveDown();
    doc.hr = () => doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.hr();
    doc.moveDown();

    // Patient and Doctor Details
    const top = doc.y;
    doc.fontSize(12).text('Patient Details:', 50, top, { underline: true });
    doc.fontSize(10).text(`Name: ${data.patient.name}`, 50, top + 20);
    doc.text(`Email: ${data.patient.email}`, 50, top + 35);
    
    doc.fontSize(12).text('Doctor Details:', 300, top, { underline: true });
    doc.fontSize(10).text(`Name: Dr. ${data.doctor.user.name}`, 300, top + 20);
    doc.text(`Specialization: ${data.doctor.specialization}`, 300, top + 35);

    doc.moveDown(4);
    doc.hr();
    doc.moveDown();

    // Appointment Details Table Header
    doc.fontSize(12).text('Appointment Summary', { align: 'center' });
    doc.moveDown();

    const tableTop = doc.y;
    doc.fontSize(10).text('Description', 50, tableTop, { bold: true });
    doc.text('Date', 250, tableTop, { bold: true });
    doc.text('Time', 350, tableTop, { bold: true });
    doc.text('Fee (NPR)', 450, tableTop, { bold: true, align: 'right' });

    doc.moveDown();
    doc.hr();
    doc.moveDown();

    // Table Content
    const contentTop = doc.y;
    doc.text('Medical Consultation', 50, contentTop);
    doc.text(new Date(data.date).toLocaleDateString(), 250, contentTop);
    doc.text(data.timeSlot, 350, contentTop);
    doc.text(`${data.fee}`, 450, contentTop, { align: 'right' });

    doc.moveDown(2);
    doc.hr();
    doc.moveDown();

    // Total
    doc.fontSize(12).text(`Total Amount: NPR ${data.fee}`, { align: 'right', bold: true });
    
    doc.moveDown(5);
    doc.fontSize(10).text('Terms & Conditions:', { underline: true });
    doc.text('1. This is a computer-generated invoice and does not require a physical signature.');
    doc.text('2. Please keep this for your medical records.');
    doc.text('3. Refunds for cancellations follow the platform policy.');

    // Footer
    doc.fontSize(8).text('HealSync - Your Trusted Healthcare Partner', 0, 750, { align: 'center', width: 600 });

    doc.end();
};

/**
 * Generate a Prescription PDF
 * @param {Object} data - Appointment data including populated patient and doctor
 * @param {String} notes - Clinical notes/prescription text
 * @param {Object} res - Express response object
 */
const generatePrescriptionPDF = (data, notes, res) => {
    const doc = new PDFDocument({ margin: 50 });

    doc.pipe(res);

    // Hospital/Platform Branding
    doc.fillColor('#10b981') // Green for medical
        .fontSize(24)
        .text('HealSync Prescription', { align: 'center' });
    
    doc.moveDown();
    doc.fillColor('#444444').fontSize(10).text(`RX ID: ${data._id.toString().substring(0, 8).toUpperCase()}`, { align: 'right' });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'right' });

    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#eeeeee').stroke();
    doc.moveDown();

    // Doctor & Patient Info
    doc.fontSize(12).fillColor('#111827').text(`Dr. ${data.doctor.user.name}`, { bold: true });
    doc.fontSize(10).text(`${data.doctor.specialization}`);
    doc.moveDown();

    doc.fontSize(10).text(`Patient Name: ${data.patient.name}`, 50);
    doc.text(`Age/Sex: Not Specified`);
    doc.moveDown();

    doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor('#eeeeee').stroke();
    doc.moveDown(2);

    // RX Symbol
    doc.fontSize(30).text('Rx', 50, doc.y - 10);
    doc.moveDown();

    // Prescription Body
    doc.fontSize(12).text(notes || 'No medications prescribed.', 70, doc.y);

    // Advice / Notes
    if (data.notes) {
        doc.moveDown(3);
        doc.fontSize(10).text('Advice:', { underline: true });
        doc.text(data.notes);
    }

    // signature area
    doc.moveDown(5);
    doc.moveTo(400, doc.y).lineTo(550, doc.y).strokeColor('#444444').stroke();
    doc.fontSize(8).text('Doctor Signature', 400, doc.y + 5, { align: 'center', width: 150 });

    // Footer
    doc.fontSize(8).text('Generated by HealSync Telemedicine System', 0, 750, { align: 'center', width: 600 });

    doc.end();
};

module.exports = { generateInvoicePDF, generatePrescriptionPDF };
